#include "BluetoothAudio.h"

#include <BluetoothA2DPSink.h>
#include <ESP_I2S.h>

#include "Config.h"
#include "Pins.h"
#include "Logger.h"

namespace
{

/**
 * @brief Global I2S interface used by the Bluetooth A2DP sink.
 *
 * The I2S peripheral is configured as a standard stereo output and
 * receives the PCM audio stream generated by the A2DP sink.
 */
I2SClass i2s;

/**
 * @brief Bluetooth A2DP sink instance.
 *
 * The sink receives audio from a Bluetooth source and forwards the
 * decoded PCM stream to the I2S interface.
 */
BluetoothA2DPSink a2dpSink(i2s);

}

namespace BluetoothAudio
{

/**
 * @brief Initializes the Bluetooth audio subsystem.
 *
 * The initialization sequence is:
 * 1. Configure the I2S GPIO pins.
 * 2. Initialize I2S in standard stereo mode.
 * 3. Start the Bluetooth A2DP sink using the configured device name.
 *
 * Audio is configured for:
 * - Sample rate: 44.1 kHz
 * - Data width: 16 bits
 * - Channel mode: Stereo
 *
 * @return true if I2S and Bluetooth initialization succeed.
 * @return false if I2S initialization fails.
 */
bool begin()
{
    Logger::info("Initializing Bluetooth Audio...");

    //==============================================
    // Configure I2S Pins
    //==============================================

    /**
     * Configure the GPIO pins used by the I2S interface.
     *
     * BCLK: Bit clock
     * LRCK: Left/right word select clock
     * DOUT: Digital audio output
     */
    i2s.setPins(
        Pins::I2S_BCLK,
        Pins::I2S_LRCK,
        Pins::I2S_DOUT
    );

    //==============================================
    // Initialize I2S
    //==============================================

    /**
     * Initialize I2S using the standard Philips-style
     * interface configuration.
     *
     * The Bluetooth A2DP sink outputs 16-bit stereo PCM
     * audio at 44.1 kHz.
     */
    if (!i2s.begin(
            I2S_MODE_STD,
            44100,
            I2S_DATA_BIT_WIDTH_16BIT,
            I2S_SLOT_MODE_STEREO,
            I2S_STD_SLOT_BOTH))
    {
        Logger::error("Failed to initialize I2S.");
        return false;
    }

    Logger::success("I2S initialized.");

    //==============================================
    // Start Bluetooth A2DP Sink
    //==============================================

    /**
     * Start the Bluetooth A2DP sink.
     *
     * The device name is obtained from Config so that
     * application-specific settings remain centralized.
     */
    a2dpSink.start(Config::BLUETOOTH_DEVICE_NAME);

    Logger::success("Bluetooth Audio initialized.");

    return true;
}

} // namespace BluetoothAudio