#ifndef TAS5822REGISTERS_H
#define TAS5822REGISTERS_H

#include <Arduino.h>

namespace TAS5822
{

/**
 * @brief PurePath Console meta-command identifiers.
 *
 * These values are not TAS5822 register addresses. They are special
 * commands used by PurePath-generated configuration data to represent
 * operations such as switching register pages, inserting delays, or
 * writing data in bursts.
 */
constexpr uint8_t CFG_META_SWITCH = 0xFF;
constexpr uint8_t CFG_META_DELAY  = 0xFE;
constexpr uint8_t CFG_META_BURST  = 0xFD;

/**
 * @brief Represents an entry in the TAS5822 configuration sequence.
 *
 * A register entry normally contains a register offset and its value.
 * When the offset matches one of the PurePath meta-command identifiers,
 * the same two bytes are interpreted as a command and its parameter.
 */
union Register
{
    struct
    {
        uint8_t offset;  ///< TAS5822 register offset.
        uint8_t value;   ///< Value to write to the register.
    };

    struct
    {
        uint8_t command; ///< PurePath meta-command identifier.
        uint8_t param;   ///< Parameter associated with the command.
    };
};

/**
 * @brief TAS5822 DSP configuration sequence.
 *
 * Contains the register entries generated by PurePath Console and used
 * to configure the TAS5822 device.
 */
extern const Register Registers[];

/**
 * @brief Number of entries in the TAS5822 DSP configuration sequence.
 */
extern const size_t RegisterCount;

} // namespace TAS5822

#endif // TAS5822REGISTERS_H